[ENG-1569] Fix Ginkgo tests
united-manufacturing-hub/benthos-umh pull request #64
Opened 2024-10-08 11:46 UTC by kanapuli

2024-10-08 16:37 UTC, kanapuli commented on opcua_plugin/opcua.go
>  		if err := g.BrowseAndSubscribeIfNeeded(ctx); err != nil {
**Note for Reviewers:** This code is somewhat complex. The function `g.BrowseAndSubscribeIfNeeded` must be completed before the `Connect` function, as it initializes `g.NodeList`. This `NodeList` is necessary for the subsequent `ReadBatch` function. If `g.BrowseAndSubscribeIfNeeded` is executed without using `sync.WaitGroup`, there is no assurance that the goroutine will finish before `ReadBatch` is called. This is a primary reason for test failures, as the goroutine may not complete, leading to an empty `NodeList` and causing `ReadBatch` to fail.

If I remove the `sync.WaitGroup` from this section and run `g.BrowseAndSubscribeIfNeeded` synchronously, the tests still fail due to some channels becoming blocked. Therefore, this section needs to be refactored in the future for improved simplicity and clarity.

2024-10-09 09:36 UTC, JeremyTheocharis requested changes

2024-10-09 09:36 UTC, JeremyTheocharis commented on opcua_plugin/opcua.go
> +		defer wg.Done()
then you can also instead remove the goroutine. would make the code a little bit cleaner

2024-10-14 15:45 UTC, JeremyTheocharis commented on opcua_plugin/opcua.go
> +	if len(g.NodeList) == 0 {
I am not a fan of this, but I can understand that it is needed for tests. Can we ensure that this never happens in production, where connect is called before ReadBatch? For example that at the end of connect we check if the nodelist is empty and if yes, disconnect again abnd return an error so that benthos tries to re-connect a couple of seconds later. then we need to update this code here to explain that this is just for tests.

Or we could also instead update all the tests so that the nodes are always there before ReadBatch is called

I am worried that this might lead to unintended side-effects like during conncet it does not find any nodes, but continues anyway. and that if the nodes later come online in the server, that they are here then suddenly browsed. However when writing about this, it actually makes sense to do it like this. Maybe still add a code comment about it?

2024-10-15 11:00 UTC, JeremyTheocharis approved these changes

2024-10-15 11:17 UTC, merged