Added support for EIO404 Bluetooth Mesh IoT Base Station.
united-manufacturing-hub/benthos-umh pull request #78
Opened 2024-11-08 08:24 UTC by EmlingerM

## Reference implementation for suggested feature: #77

### Breaking Changes:

Instead of using only the port number as the unique identifier for connected devices, the entire URI will be used.

e.g. `string: /iolinkmaster/port[1]/` or `string: /meshnetwork/mesh_adapter[1]/iolinkmaster/port[1] `

This replaces the previous method of using eg. `int: 1` to identify a connected sensor.

2024-11-08 10:45 UTC, EmlingerM commented
Ok sorry for confusion.

This PR should not disrupt existing functionality. I have tested the code with both the EIO404 + EIO344  and AL1352 models, using various sensors.

The concept stays the same as before:

The logic remains consistent with previous implementations:

- When querying the portMode for "physical ports" on the EIO404 (e.g., /iolinkmaster/port[1]/), the EIO404 returns a status code indicating that the port does not exist or is not connected.
- Similarly, if you request the portMode for a Bluetooth Adapter  (e.g., /meshnetwork/mesh_adapter[1]/iolinkmaster/port[1]/), on a normal AL1352, it returns the same status code indicating that this no Bluetooth adapter are connected. 

This approach mirrors the previous behavior observed with the AL1350 (4 ports) and AL1352 (8 ports),


It would be possible change this logic to first query the specific model and then request only the portModes of the existing "ports" However, this would lead to a larger conceptual changes.

2024-11-08 13:29 UTC, JeremyTheocharis commented
alright, let me check it by looking into the code

also ENG-1909 (ignore this, just for our internal ticketing system)

2024-11-08 13:37 UTC, JeremyTheocharis requested changes
Thank you for the PR! this is a nice addon, and tbh I did not even knew this hardware from ifm existed. 

I added some comments, mostly about comments and edge cases. I hope this does not discourage you from openeing more PRs. if yes, please tell em and I implement the changes myself.

2024-11-08 13:37 UTC, JeremyTheocharis commented on sensorconnect_plugin/downloadPortModeData.go
> +	// Note that each EIO344 Bluetooth Mesh IO-Link Adapter is limited to a single IO-Link port.
Can you add here the note that you wrote me, that the EIO404 will ignore the `/iolinkmaster/port[%d]/mode` data points and vice versa? I think it would help here for understanding, that we expect to get a lot of 400 error codes back.

2024-11-08 13:37 UTC, JeremyTheocharis commented on sensorconnect_plugin/downloadPortModeData.go
> +	badgeSize := 50
why 50? maybe put this as constant in the header with a short explanation

2024-11-08 13:37 UTC, JeremyTheocharis commented on sensorconnect_plugin/downloadPortModeData.go
> +			return result, err
if one of the requests fails, then it will send back the result array up to this moment, and an error message. but then we would have inconsistent amount of messages.

wouldn't it be better to continue here to let all the other requests execute as well. and then additionally return all errors? then if always the same port / message / batch fails ,all the others will continue to work

2024-11-08 13:37 UTC, JeremyTheocharis commented on sensorconnect_plugin/downloadPortModeData.go
> +func extractPort(input string) (string, error) {
can you put a quick function comment? a basic one from chatgpt is fine. it should answer why we need this function (not what the function does)

2024-11-08 13:37 UTC, JeremyTheocharis commented on sensorconnect_plugin/downloadPortModeData.go
> +func extractBluetoothAdapter(input string) (string, error) {
see comment for extractPort

2024-11-11 09:52 UTC, EmlingerM commented on sensorconnect_plugin/downloadPortModeData.go
> +			return result, err
Yes good point. 👍 

I've changed this.

2024-11-12 10:44 UTC, JeremyTheocharis commented
We are currently trying out coderabbit, so I am going to let this "test" on your PR. No need to actually change something because of it, it is pure optional. But we saw it in other PRs that it was really helpful.

@coderabbitai

2024-11-12 10:45 UTC, JeremyTheocharis approved these changes

2024-11-12 15:02 UTC, merged